config/routes.rb
Rails.application.routes.draw do
  get 'equipos/index'
  get 'equipos/new'
  get 'equipos/create'
  get 'equipos/show'
  get 'equipos/edit'
  get 'equipos/update'
  get 'equipos/destroy'
  root 'main#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :index]
  resources :equipos

  get 'main/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipo.rb
class Equipo < ApplicationRecord
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :bigint(8)        not null, primary key
#  nombre     :string(255)
#  fecha      :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#

class Project < ApplicationRecord
  belongs_to :user
  validates :nombre, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  name            :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password validations: false

  validates :name, presence: true
  validates :email, uniqueness: true, format: /@/
  validates :password, presence: true, on: :create
  validates :password, length: { in: 6..20 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def sign_in(user)
  cookies.permanent.signed[:user_id] = user.id
  @current_user = user
end

def sign_out
  cookies.delete(:user_id)
  @current_user = nil
end

private
  def signed_in?
    !current_user.nil?
  end
  helper_method :signed_in?

  def current_user
    @current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
  rescue ActiveRecord::RecordNotFound
  end
  helper_method :current_user

  def private_access
     redirect_to :login unless signed_in?
  end

  def public_access
     redirect_to root_path if signed_in?
  end
end

app/controllers/equipos_controller.rb
class EquiposController < ApplicationController
  before_action :private_access, except: [:index, :show]

    def index
      @equipo = Equipo.all
    end

    def show
      @p = Equipo.find(params[:id])
    end

    def new
      @p=Equipo.new
    end

    def create
      @p=Equipo.new(equipo_params)
      if @p.save
        redirect_to equipo_path(@p), notice: "Se ha creado el equipo exitosamente"
      else
      puts "No se pudo guardar"
      end
    end

    def edit
      @p = Equipo.find(params[:id])
    end

    def update
      @p = Equipo.find(params[:id])
      if @p.update(equipo_params)
        redirect_to equipo_path(@p), notice: "Se ha guardado el equipo exitosamente"
      else
        render :edit
      end
    end

    def destroy
      project = Equipo.find(params[:id])
      project.destroy
      redirect_to equipo_path, alert: "El equipo se ha eliminado correctamente"
    end

  private
    def equipo_params
      params.require(:equipo).permit(:nombre, :serial, :fecha, :marca, :modelo, :descripcion)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

before_action :private_access, except: [:index, :show]

  def index
    @projects = Project.all
  end

  def show
    @p = Project.find(params[:id])
  end

  def new
    @p=Project.new
  end

  def create
    @p=Project.new(project_params)
    @p.user=current_user
    if @p.save
      redirect_to project_path(@p), notice: "Se ha creado el proyecto exitosamente"
    else
    puts "No se pudo guardar"
    end
  end

  def edit
    @p = Project.find(params[:id])
  end

  def update
    @p = Project.find(params[:id])
    if @p.update(project_params)
      redirect_to project_path(@p), notice: "Se ha guardado el proyecto exitosamente"
    else
      render :edit
    end
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to projects_path, alert: "El proyecto se ha eliminado correctamente"
  end

private
  def project_params
    params.require(:project).permit(:nombre, :introduccion, :planteamiento, :antecedentes, :justificacion, :marco_teorico, :objetivos, :desarrollo, :conclusiones, :referencias)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :private_access, only: [:destroy]
before_action :public_access, except: [:destroy]

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
    sign_in(user)
    redirect_to equipos_path
    @opciones = false
    else
    flash[:success] = "Correo o contraseña incorrecta"
    render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
    @opciones = true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "Se ha creado el usuario exitosamente"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, alert: "El usuario se ha eliminado correctamente"
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :name, :rol)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/equipos/create.html.erb
<h1>Equipos#create</h1>
<p>Find me in app/views/equipos/create.html.erb</p>

app/views/equipos/destroy.html.erb
<h1>Equipos#destroy</h1>
<p>Find me in app/views/equipos/destroy.html.erb</p>

app/views/equipos/edit.html.erb
<h1>Equipos#edit</h1>
<p>Find me in app/views/equipos/edit.html.erb</p>

app/views/equipos/index.html.erb
<div style="margin-top: 150px margin-left:10px">
  <br>
  <br>
  <label class="control-label col-sm-3" style="font-family:Georgia; font-size:16px" for="user">Código o Nombre del Equipo:</label>
  <input class="col-sm-6 col-sm-offset-0" type="text" id="myInput" onkeyup="myFunction()" title="Escriba un nombre o código de equipo...">
</div>
<br>
<br>
<div class="container">
<h2>Listado de Equipos Disponibles</h2>
  <table class="table table-striped col-sm-0 col-sm-offset-0" id="myTable">
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Serial</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Descripción</th>
      <th>Disponible</th>
    </tr>
    <% @equipo.each do |equipo| %>
      <tr>
        <td><%= equipo.id %></td>
        <td><%= equipo.nombre %></td>
        <td><%= equipo.serial %></td>
        <td><%= equipo.marca %></td>
        <td><%= equipo.modelo %></td>
        <td><%= equipo.descripcion %></td>
        <td><% if equipo.disponibilidad===true %>
                <button type="button" class="btn btn-success glyphicon glyphicon-ok" data-toggle="modal" data-target="#ModalTrue"></button>
                <!-- Modal -->
                  <div class="modal fade" id="ModalTrue" role="dialog">
                  <div class="modal-dialog">

                <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h3 align="center" class="modal-title">Confirmar Alquiler</h3>
                    </div>
                    <div class="modal-body">
                      <p>¿Estás seguro que deseas alquilar este equipo?</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
                      <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    </div>
                  </div>

                  </div>
                  </div>
            <% elsif equipo.disponibilidad===false %>
                <button type="button" class="btn btn-danger glyphicon glyphicon-remove" data-toggle="modal" data-target="#ModalFalse"></button>
                <!-- Modal -->
                  <div class="modal fade" id="ModalFalse" role="dialog">
                  <div class="modal-dialog">

                <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h3 align="center" class="modal-title">Aviso Importante</h3>
                    </div>
                    <div class="modal-body">
                      <p>Lo sentimos, este equipo no se encuentra disponible.</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
                    </div>
                  </div>

                  </div>
                  </div>
            <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<script>
  function myFunction() {
    var input, filter, table, tr, td, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[1];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }
    }
}
</script>

app/views/equipos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Crear Equipo</h1>

      <% if @p.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @p.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

        <%=form_for @p do |f| %>
            <div class="form-group">
              <%= f.text_field :nombre, class: "form-control input-lg", placeholder: "Nombre del equipo"%>
            </div>
            <div class="form-group">
              <%= f.text_field :serial, class: "form-control input-lg", placeholder: "Serial del equipo"%>
            </div>
            <div class="form-group">
              <%= f.text_field :fecha, class: "form-control input-lg", placeholder: "Fecha del equipo"%>
            </div>
            <div class="form-group">
              <%= f.text_field :marca, class: "form-control input-lg", placeholder: "Marca del equipo"%>
            </div>
            <div class="form-group">
              <%= f.text_field :modelo, class: "form-control input-lg", placeholder: "Modelo del equipo"%>
            </div>
            <div class="form-group">
              <%= f.text_field :descripcion, class: "form-control input-lg", placeholder: "Pequeña descripción del equipo"%>
            </div>
            <div class="form-group">
            <%= f.submit "Crear Equipo", class: "btn btn-success btn-lg btn-block" %>
            </div>
        <% end %>
        </div>
      </div>
    </div>

app/views/equipos/show.html.erb
<h1>Equipos#show</h1>
<p>Find me in app/views/equipos/show.html.erb</p>

app/views/equipos/update.html.erb
<h1>Equipos#update</h1>
<p>Find me in app/views/equipos/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>TecnoRenting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
  </head>
  <body>
    <!--Creación de la barra de navegación-->
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
    <a class="navbar-brand">TecnoRenting</a>
  </div>

  <ul class="nav navbar-nav">
    <% if signed_in? %>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Equipo
      <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Consultar", equipos_path %></li>
        <li><%= link_to "Crear", new_equipo_path%></li>
      </ul>
    </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Usuarios
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Consultar", users_path %></li>
          <li><%= link_to "Crear", new_user_path %></li>
        </ul>
        </li>
  </ul>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "<span class='glyphicon glyphicon-user'></span> Cerrar Sesión ".html_safe, logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "<span class='glyphicon glyphicon-log-in'></span> Iniciar Sesión ".html_safe, login_path, method: :new %></li>
      <li><%= link_to "<span class='glyphicon glyphicon-thumbs-up'></span> Regístrate ".html_safe, new_user_path %></li>
    <% end %>
  </ul>
</div>
</nav>
<% if signed_in? %>
  <div align="center" class="col-sm-offset-1"><h4>Hola <%=current_user.name%></h4></div>
<% end %>
<dt><h1 style="font-family:Dosis;" class="col-sm-4 col-sm-offset-0"></h1></dt>
<% if flash[:notice] %>
  <div class="col-sm-6 col-sm-offset-3">
    <div class="alert alert-success alert-dismissible"><%= flash[:notice] %>
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
  </div>
<% end %>
          <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
  <div class="jumbotron">
    <h1 style="font-family:Dosis;">TecnoRenting ®</h1>
    <h5>Este aplicativo tiene como objetivo gestionar y administrar el alquiler de equipos tecnológicos para empresas.</h5>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= form_for @p do |f| %>
      <h1><%= @p.nombre %></h1>
        <div class="form-group">
          <label class="control-label col-sm-6">Nombre del Proyecto</label>
          <%= f.text_field :nombre, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Introducción</label>
          <%= f.text_area :introduccion, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Planteamiento del Problema</label>
          <%= f.text_area :planteamiento, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Antecedentes</label>
          <%= f.text_area :antecedentes, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Justificación</label>
          <%= f.text_area :justificacion, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Marco Teórico</label>
          <%= f.text_area :marco_teorico, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Objetivos</label>
          <%= f.text_area :objetivos, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Desarrollo</label>
          <%= f.text_area :desarrollo, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Conclusiones</label>
          <%= f.text_area :conclusiones, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Referencias</label>
          <%= f.text_area :referencias, class: "form-control input-lg" %>
        </div>
          <%= f.submit "Modificar Proyecto", class: "btn btn-success btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div style="margin-top: 150px margin-left:10px">
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <label class="control-label col-sm-2" style="font-family:Georgia; font-size:16px" for="user">Código o Nombre del Proyecto:</label>
  <input type="text" id="myInput" onkeyup="myFunction()" title="Escriba un nombre de proyecto">
</div>
<!-- <form class="form-horizontal" action="/action_page.php" style="margin-top:250px">
    <div class="form-group">
      <label class="control-label col-sm-2" style="font-family:Georgia;" for="user">Código del Proyecto:</label>
      <div class="col-sm-4">
        <input type="user" class="form-control" id="usuario" placeholder="Digite el código del proyecto">
        <br>
        <p>
          <button type="button" class="btn btn-info">
            <span class="glyphicon glyphicon-search"></span> Consultar
          </button>
        </p>
      </div>
    </div>
  </form> -->

<div class="container">
<h2>Listado de Proyectos Inscritos</h2>
  <table class="table table-striped" id="myTable">
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Fecha de Creación</th>
      <th>Fecha de Última Actualización</th>
    </tr>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.id %></td>
        <td><%= link_to project do %><div data-toggle="tooltip" title="Ver mas..."></div><%=project.nombre %><% end %></td>
        <td><%= project.created_at %></td>
        <td><%= project.updated_at %></td>
      </tr>
    <% end %>
  </table>
</div>

<script>
  function myFunction() {
    var input, filter, table, tr, td, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[1];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }
    }
}
</script>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Crear Proyecto</h1>

      <% if @p.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @p.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

        <%=form_for @p do |f| %>
          <div class="form-group">
            <%= f.text_field :nombre, class: "form-control input-lg", placeholder: "Nombre del proyecto"%>
          </div>
            <%= f.submit "Crear Proyecto", class: "btn btn-success btn-lg btn-block" %>
          </div>
        <% end %>
        </div>
      </div>
    </div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="progress">
        <% multiplicador = 1.1 %>
        <% if @p.introduccion=="" && @p.planteamiento == "" && @p.antecedentes == "" && @p.justificacion == "" && @p.marco_teorico == "" && @p.objetivos == "" && @p.desarrollo == "" && @p.conclusiones == "" && @p.referencias == ""%>
          <div class="progress-bar progress-bar-danger progress-bar-striped active" role="progress-bar-danger" aria-valuenow="0" aria-valuemin="0"
            aria-valuemax="100" style="width:5%">0%
          </div>
        <% else if @p.introduccion != ""%>
          <div class="progress-bar progress-bar-striped active" role="progress-bar-danger" aria-valuenow="0" aria-valuemin="0"
            aria-valuemax="100" style="width:<%= 10 %>">10%
          </div>
        <% end %>
      </div>
      <%= form_for @p do |f| %>
      <h1><%= @p.nombre %></h1>
      <% if signed_in? && @p.user == current_user %>
        <div align="right">
          <%= link_to "<span style='font-size: 25px' class='glyphicon glyphicon-pencil' data-toogle='tooltip' title='Editar Equipo'></span>".html_safe, edit_project_path(@p) %>
        </div>
      <% end %>
        <div class="form-group">
          <label class="control-label col-sm-6">Introducción</label>
          <%= f.text_area :introduccion, class: "form-control input-lg", readonly: "true"%>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Planteamiento del Problema</label>
          <%= f.text_area :planteamiento, class: "form-control input-lg", readonly: "true"%>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Antecedentes</label>
          <%= f.text_area :antecedentes, class: "form-control input-lg", readonly: "true"%>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Justificación</label>
          <%= f.text_area :justificacion, class: "form-control input-lg", readonly: "true"%>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Marco Teórico</label>
          <%= f.text_area :marco_teorico, class: "form-control input-lg", readonly: "true"%>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Objetivos</label>
          <%= f.text_area :objetivos, class: "form-control input-lg", readonly: "true"%>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Desarrollo</label>
          <%= f.text_area :desarrollo, class: "form-control input-lg", readonly: "true"%>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Conclusiones</label>
          <%= f.text_area :conclusiones, class: "form-control input-lg", readonly: "true"%>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-6">Referencias</label>
          <%= f.text_area :referencias, class: "form-control input-lg", readonly: "true"%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<br>
<br>
<br>
<br>
  <div class="container">
    <h2>Listado de Usuarios Creados</h2>
      <table class="table table-striped">
        <tr>
          <th>Id</th>
          <th>Usuario</th>
          <th>Nombre</th>
          <th>Rol</th>
          <th>Fecha de Creación</th>
        </tr>
      <% @user.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>
          <td><%= user.name %></td>
          <td><%= user.rol %></td>
          <td><%= user.created_at %></td>
        </tr>
      <% end %>
      </table>
  </div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Crear Cuenta</h1>

      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.email_field :email, class: "form-control input-lg", placeholder: "Email" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, class: "form-control input-lg", placeholder: "Contraseña" %>
        </div>

        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre" %>
        </div>

        <div class="form-group">
          <%= f.select :rol, ["Administrador", "Cliente"], {:prompt => 'Rol de Usuario'}, class: "btn btn-danger dropdown-toggle" %>
        </div>
        <br>
        <div class="actions">
          <%= f.submit 'Crear Usuario', class: "btn btn-primary btn-block btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>